version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://mongo:27017/effective-mobile-junior-node-js
      - NODE_ENV=production
      - HTTP_PORT=${HTTP_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    ports:
      - '${HTTP_PORT:-5000}:5000'
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: effective-mobile-junior-node-js
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo-data:
